# Generated by Django 4.2.6 on 2023-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_index_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='логотип'),
            preserve_default=False,
        ),
    ]
