# Generated by Django 4.2.6 on 2023-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='eighth',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='фото на главной странице'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='fifth',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='бекенд разработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='first',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='фулстак разработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='forth',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='андроид разработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='second',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='дизайнер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='seventh',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='фото на главной странице'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='sixth',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='тестировшик по'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='third',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='основы програмирования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='first_photo',
            field=models.ImageField(upload_to='logo_image/', verbose_name='фронтент разработчик'),
        ),
    ]
