# Generated by Django 4.2.6 on 2023-11-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photos_eighth_photos_fifth_photos_first_photos_forth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
